dairy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('dairyapp.urls')),
    path('admin/', admin.site.urls),
]

dairyapp/urls.py
from django.urls import path, include
from . import views

app_name='dairyapp'

urlpatterns=[
    path('',views.index,name='index'),
    path('milkpurchase/',views.milkPurchase,name='milk-purchase'),
    path('milkpurchase/<id>/delete',views.milkPurchaseDelete,name='delete-purchase'),
    path('addmilkproducts/',views.addMilkProducts,name='add-milk-products'),
    path('sellmilkproducts/',views.sellMilkProducts,name='sell-milk-products'),
    path('sellmilkproducts/<id>/delete',views.mProductSellDelete,name='delete-sales'),
    path('stockrecords/<id>',views.mStockDetailView,name='stock-detail'),
    path('operationcost/',views.operationCost,name='operation-cost'),
    path('operationcost/<id>/delete',views.deleteOperationCost,name='delete-operation-cost'),
    path('report/', views.report, name='report'),
    path('report/purchasereport/',views.purchaseReport,name='purchase-report'),
    path('report/stockreport/',views.stockReport,name='stock-report'),
    path('report/salesreport/',views.salesReport,name='sales-report'),
    path('report/operationcostreport',views.operationCostReport,name='operationcost-report'),
    path('settings/',views.settings,name='settings'),
    path('settings/createproduct',views.newProductCreateView.as_view(), name='create-product'),
    path('settings/createproductunit',views.newProductUnitCreate, name='create-product-unit'),
    path('test/',views.test,name='test'),
    #path('stockrecords/<id>/delete',views.mStockRecordDelete,name='delete-stock-records'),

]

dairyapp/models.py
from django.db import models
from django.utils import timezone
from dairyapp.choices import MILK_CHOICES
import datetime

# Create your models here.

class Customer(models.Model):
    customer_id=models.AutoField(primary_key=True)
    customer_name=models.CharField(max_length=50)
    customer_address=models.CharField(max_length=100)
    customer_contact=models.CharField(max_length=10)


    def __str__(self):
        return self.customer_name


## Milk Product Units
class mProductUnit(models.Model):
    mProductUnit_id=models.AutoField(primary_key=True)
    mProductUnit_name=models.CharField(max_length=10)

    def __str__(self):
        return self.mProductUnit_name

## Milk Products
class mProduct(models.Model):
    # KILOGRAM='kg.'
    # LITER='ltr'
    # PACKET='pkt'
    #
    # MILK_PRODUCTS_UNIT_CHOICES=(
    #     (KILOGRAM,'Kilogram'),
    #     (LITER,'Liter'),
    #     (PACKET,'Packet'),
    # )

    mProduct_id=models.AutoField(primary_key=True)
    mProduct_name=models.CharField(max_length=50)
    mProduct_qtyunit = models.ForeignKey(mProductUnit,on_delete=models.CASCADE) #Product Unit has one to many relationship with mProduct
    mProduct_qty=models.FloatField(default=0) ##current stock
    #mProduct_qtyunit=models.CharField(max_length=3,choices=MILK_PRODUCTS_UNIT_CHOICES,default=LITER)  ##unit type eg. ltr, kg, ml



    def __str__(self):
        return self.mProduct_name


##milk purchase
class mPurchase(models.Model):

    mPurchase_id=models.AutoField(primary_key=True)
    seller=models.CharField(max_length=50)
    mPurchase_date=models.DateField(blank=True,null=True)
    mPurchase_product=models.CharField(max_length=15,choices=MILK_CHOICES)
    mPurchase_qty=models.FloatField()
    mPurchase_rate=models.FloatField()
    mPurchase_total=models.FloatField(default=0)

    def __str__(self):
        return self.seller

## Dairy Stock Add
class mStock(models.Model):
    mStock_id=models.AutoField(primary_key=True)
    mStock_date=models.DateTimeField(default=timezone.now)
    mStock_product=models.ForeignKey(mProduct,on_delete=models.CASCADE)
    mStock_qty=models.FloatField()

    # try to access unit using mProduct.mProduct_qtyunit
    ## not sure here if it works !!
    ## check and verify it later



## milk product sell
class mProductSell(models.Model):
    mProductSell_id = models.AutoField(primary_key=True)

    buyer_name=models.CharField(max_length=50,default='TBD')
    milk_product = models.ForeignKey(mProduct, on_delete=models.CASCADE)
    ## automatically set the field to now when the object is created
    mProductSell_date=models.DateField(blank=True,null=True,default=datetime.date.today)
    mProductSell_qty=models.FloatField()
    mProductSell_qtyunit=models.CharField(max_length=10,default='TBD')
    mProductSell_rate=models.FloatField()
    mProductSell_amount=models.FloatField(default=0)

    def __str__(self):
        return self.buyer_name


class operationCost(models.Model):
    operationCost_id=models.AutoField(primary_key=True)
    particular=models.CharField(max_length=80)
    date=models.DateField(blank=True,null=True,default=datetime.date.today)
    qty=models.FloatField()
    rate=models.FloatField()
    amount=models.FloatField()

    def __str__(self):
        return self.particular


class test(models.Model):
    test_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=50)
    date=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

dairyapp/views.py
from .forms import mPurchaseForm,mStockForm,mProductSellForm, operationCostForm,testForm,dateForm, addProductForm,addProductUnitForm
from .models import mPurchase,mProduct,mStock, mProductSell, mProduct, mProductUnit,test
from .models import operationCost as operationCostModel
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views import generic
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.contrib.messages.views import SuccessMessageMixin
from bootstrap_modal_forms.mixins import PassRequestMixin


## index view
def index(request):
    title='DAIRY'
    context={
        'title':title
    }
    return render(request,'dairyapp/index.html',context)

##milk purchase view
def milkPurchase(request):
    title='Buy Milk'
    milk_list = mPurchase.objects.all().order_by('-mPurchase_date')

    if request.method=='POST':
        form=mPurchaseForm(request.POST)
        if form.is_valid():
            m=form.save(commit=False)
            ## gives object bound to form
            ## commit = False means it gives object that has not been saved in db yet
            ##m.mPurchase_date=timezone.now()
            m.mPurchase_total=m.mPurchase_qty*m.mPurchase_rate
            m.save()
            return redirect('/milkpurchase')

    else:
        form=mPurchaseForm()

    ## Pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(milk_list, 10)

    try:
        milk = paginator.page(page)
    except PageNotAnInteger:
        milk = paginator.page(1)
    except EmptyPage:
        milk = paginator.page(paginator.num_pages)

    context = {
        'title': title,
        'form': form,
        'milk': milk

    }

    return render(request,'dairyapp/milk-purchase.html',context)

## Delete Purchase Information
def milkPurchaseDelete(request,id):
    mPurchase.objects.get(mPurchase_id=id).delete()
    return redirect('/milkpurchase')


### stock add
def addMilkProducts(request):
    title='Add Milk Products'
    product=mProduct.objects.all().order_by('-mProduct_name')

    if request.method=='POST':
        form=mStockForm(request.POST)
        if form.is_valid():
            m=form.save(commit=False)
            ## gives object bound to form
            ## commit = False means it gives object that has not been saved in db yet
            mProduct_name=form.cleaned_data.get('mStock_product')
            ##m.mStock_date=timezone.now()
            p=get_object_or_404(mProduct,mProduct_name=mProduct_name)
            qty=form.cleaned_data.get('mStock_qty')
            p.mProduct_qty=p.mProduct_qty+qty  ##update stock

            p.save()
            m.save()
            messages.info(request, 'Product Successfully Added to Stock')

            return redirect('/addmilkproducts')

    else:
        form=mStockForm()
    context={
        'title':title,
        'product':product,
        'form':form,
    }
    return render(request,'dairyapp/add-milk-products.html',context)

## Detail view for stock records
def mStockDetailView(request,id):
    model=mStock
    m=get_object_or_404(mProduct,mProduct_id=id)
    stock_list=mStock.objects.filter(mStock_product=m.mProduct_id).order_by('-mStock_date')
    ## Pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(stock_list, 10)

    try:
        stock = paginator.page(page)
    except PageNotAnInteger:
        stock = paginator.page(1)
    except EmptyPage:
        stock = paginator.page(paginator.num_pages)

    context={
        'm':m,
        'stock':stock,
    }

    return render(request,'dairyapp/stock-details.html',context)

# ## Delete stock logs
# def mStockRecordDelete(request,id):
#     mStock.objects.get(mStock_id=id).delete()
#     # m = get_object_or_404(mProduct, mProduct_id=mid)
#     # stock = mStock.objects.filter(mStock_id=id)
#     # m.mProduct_qty=m.mProduct_qty-stock.mStock_qty
#     # m.save()
#
#     # context = {
#     #     'm': m,
#     #     'stock': stock,
#     # }
#     # if not stock:
#     return redirect('/addmilkproducts')

    #return render(request, 'dairyapp/stock-details.html', context)

## sell milk products view
def sellMilkProducts(request):
    title='Sell Milk Products'
    sales_list=mProductSell.objects.all().order_by('-mProductSell_date')
    if request.method=='POST':
        form=mProductSellForm(request.POST)
        if form.is_valid():
            m=form.save(commit=False)
            ## gives object bound to form
            ## commit = False means it gives object that has not been saved in db yet
            milk_product = form.cleaned_data.get('milk_product')
            ##m.mProductSell_date=timezone.now()
            p=get_object_or_404(mProduct,mProduct_name=milk_product)
            qty=form.cleaned_data.get('mProductSell_qty')
            rate=form.cleaned_data.get('mProductSell_rate')
            m.mProductSell_amount=qty*rate

            ## update only if stock is available
            if (p.mProduct_qty>=qty):
                p.mProduct_qty=p.mProduct_qty-qty  ##update stock
                m.mProductSell_qtyunit=p.mProduct_qtyunit
                p.save()
                m.save()
                messages.info(request, 'Product Successfully sold')
                return redirect('/sellmilkproducts')
            else:
                messages.warning(request,'Product Quantity not available in stock')


    else:
        form=mProductSellForm()

    ## Pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(sales_list, 10)

    try:
        sales = paginator.page(page)
    except PageNotAnInteger:
        sales = paginator.page(1)
    except EmptyPage:
        sales = paginator.page(paginator.num_pages)

    context={
        'title':title,
        'form':form,
        'sales':sales,
    }
    return render(request,'dairyapp/sell-milk-products.html',context)


## Delete sales record of a product
def mProductSellDelete(request,id):

    sale=mProductSell.objects.get(mProductSell_id=id)
    p = get_object_or_404(mProduct, mProduct_name=sale.milk_product)
    p.mProduct_qty=p.mProduct_qty+sale.mProductSell_qty
    p.save()  ##Update product stock while deleting sale record
    sale.delete()
    ##Deletes the sales instance from database

    return redirect('/sellmilkproducts')

## operation cost view
def operationCost(request):
    title='Operation Cost'
    operations_list=operationCostModel.objects.all().order_by('-date')

    if request.method=='POST':
        form=operationCostForm(request.POST)
        if form.is_valid():
            m=form.save(commit=False)
            ## gives object bound to form
            ## commit = False means it gives object that has not been saved in db yet
            #m.date=timezone.now()
            qty=form.cleaned_data.get('qty')
            rate=form.cleaned_data.get('rate')
            m.amount=qty*rate
            m.save()
            messages.info(request, 'Record Successfully Added')
            return redirect('/operationcost')

    else:
        form=operationCostForm()

    ## Pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(operations_list, 10)

    try:
        operations = paginator.page(page)
    except PageNotAnInteger:
        operations = paginator.page(1)
    except EmptyPage:
        operations = paginator.page(paginator.num_pages)

    context={
        'title':title,
        'form': form,
        'operations':operations,


    }
    return render(request,'dairyapp/operationcost.html',context)

## Delete Operation Cost Records
def deleteOperationCost(request,id):
    operationCostModel.objects.get(operationCost_id=id).delete()
    return redirect('/operationcost')

## Report Page

def report(request):
    title='REPORT'
    context={
        'title':title
    }
    return render(request,'dairyapp/report.html',context)

## purchase report
def purchaseReport(request):
    title='Purchase Report'
    milk=mPurchase.objects.all().order_by('-mPurchase_date')[:10]

    if request.method=='POST':
        form=dateForm(request.POST)

        if form.is_valid():
            f=form.cleaned_data
            ## now f is a dictionary
            dateFrom=f.get('fromdate')
            dateTo=f.get('todate')
            ## filter by start and stop date
            milk=mPurchase.objects.filter(mPurchase_date__gte=dateFrom,
                                          mPurchase_date__lte=dateTo).order_by('-mPurchase_date')

            if not milk:
                messages.info(request, 'No Records Found')


    else:
        form = dateForm()

    context = {
        'title': title,
        'form': form,
        'milk': milk,
    }
    return render(request,'dairyapp/purchase-report.html',context)

##stock report
def stockReport(request):
    title='Stock Report'
    stock = mStock.objects.all().order_by('-mStock_date')[:10]

    if request.method == 'POST':
        form = dateForm(request.POST)

        if form.is_valid():
            f = form.cleaned_data
            ## now f is a dictionary
            dateFrom = f.get('fromdate')
            dateTo = f.get('todate')
            ## filter by start and stop date
            stock = mStock.objects.filter(mStock_date__gte=dateFrom,
                                            mStock_date__lte=dateTo).order_by('-mStock_date')

            if not stock:
                messages.info(request, 'No Records Found')


    else:
        form = dateForm()

    context = {
        'title': title,
        'form': form,
        'stock': stock,
    }
    return render(request, 'dairyapp/stock-report.html',context)

##sales report
def salesReport(request):
    title='Sales Report'

    sales = mProductSell.objects.all().order_by('-mProductSell_date')[:10]

    if request.method == 'POST':
        form = dateForm(request.POST)

        if form.is_valid():
            f = form.cleaned_data
            ## now f is a dictionary

dairyapp/templates/dairyapp/settings/add-product.html
<form method="post"  enctype="multipart/form-data">
  {% csrf_token %}

 <div class="modal-header">
    <h5 class="modal-title"><strong>Create/Add New Product</strong></h5>
     <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    {% for field in form %}
      <div class="form-group{% if field.errors %} invalid{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        {% for error in field.errors %}
          <p class="help-block text-danger">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}

  <div>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="button" class="submit-btn btn btn-primary">Create</button>
  </div>
  </div>



</form>

dairyapp/templates/dairyapp/settings/add-unit.html
{% extends 'dairyapp/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block main-content %}
    <h2><strong>{{ title }}</strong></h2>
    <div class="row">
        <div class="col-lg-5 col-lg-offset-1">
            <form class="form-horizontal" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                {% endfor %}

                {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                            {{ error }}

                        {% endfor %}
                    </div>
                {% endif %}

                {% for field in form %}

                    <div class="form-group">

                        {{ field.label_tag }}
                        {% if form.is_bound %}
                            {% if field.errors %}

                                {% render_field field class="form-control is-invalid"%}

                                {% for error in field.errors %}
                                    <div class="invalid-feedback text-danger">
                                         {{ error }}
                                    </div>
                                {% endfor %}

                            {% else %}
                                   {% render_field field class="form-control is-valid" %}
                            {% endif %}

                        {% else %}
                               {% render_field field class="form-control" %}
                        {% endif %}

                    {% if field.help_text %}

                        <small class="form-text text-primary">{{ field.help_text }}</small>
                    {% endif %}

                    </div>
                {% endfor %}



                <div class="form-group">
                    <div class="col-sm-12" onclick="if (!confirm('Are you sure?')) { return false }">
                         <button type="submit" class="btn btn-primary btn-block" >
                             <strong>Create</strong>
                         </button>
                    </div>
                 </div>

            </form>
        </div>

    </div>

{% endblock %}

dairyapp/templates/dairyapp/settings/index.html
{% extends 'dairyapp/base.html' %}


{% load static %}
{% load widget_tweaks %}

{% block extra-css %}

<style>

.myButton {
	-moz-box-shadow:inset 0px 0px 0px 0px #caefab;
	-webkit-box-shadow:inset 0px 0px 0px 0px #caefab;
	box-shadow:inset 0px 0px 0px 0px #caefab;
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #77d42a), color-stop(1, #5cb811));
	background:-moz-linear-gradient(top, #77d42a 5%, #5cb811 100%);
	background:-webkit-linear-gradient(top, #77d42a 5%, #5cb811 100%);
	background:-o-linear-gradient(top, #77d42a 5%, #5cb811 100%);
	background:-ms-linear-gradient(top, #77d42a 5%, #5cb811 100%);
	background:linear-gradient(to bottom, #77d42a 5%, #5cb811 100%);
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#77d42a', endColorstr='#5cb811',GradientType=0);
	background-color:#77d42a;
	-moz-border-radius:24px;
	-webkit-border-radius:24px;
	border-radius:24px;
	border:1px solid #268a16;
	display:inline-block;
	cursor:pointer;
	color:#306108;
	font-family:Arial;
	font-size:15px;
	font-weight:bold;
	padding:13px 53px;
	text-decoration:none;
	text-shadow:0px 1px 0px #aade7c;
}
.myButton:hover {
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #5cb811), color-stop(1, #77d42a));
	background:-moz-linear-gradient(top, #5cb811 5%, #77d42a 100%);
	background:-webkit-linear-gradient(top, #5cb811 5%, #77d42a 100%);
	background:-o-linear-gradient(top, #5cb811 5%, #77d42a 100%);
	background:-ms-linear-gradient(top, #5cb811 5%, #77d42a 100%);
	background:linear-gradient(to bottom, #5cb811 5%, #77d42a 100%);
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#5cb811', endColorstr='#77d42a',GradientType=0);
	background-color:#5cb811;
}
.myButton:active {
	position:relative;
	top:1px;
}


.myfont{
            font-size: 18px;


        }

tr:hover{

            font-weight: bolder;
}
</style>


{% endblock %}

{% block main-content %}

    <div class="row">
        <h2 class="col-lg-offset-1"><strong>{{ title }}</strong></h2>
        <div class="col-lg-10 col-lg-offset-2">
        <div class="modal fade" tabindex="-1"  style="width:800px;margin:0 auto;" role="dialog" id="modal">
          <div class="modal-dialog" role="document">
            <div class="modal-content">

            </div>
          </div>
        </div>
        <button class="create-product myButton" type="button" name="button">Create/Add new Product</button>
        </div>
    </div>
    <!--create new product ends here-->
    <!-- create new product unit starts here -->
    <div class="row " style="margin-top: 20px;">
        <div class="col-lg-10 col-lg-offset-2">

                <a href="{% url 'dairyapp:create-product-unit' %}" >

                  <button class="myButton" type="button" name="button">Create/Add new Product Unit</button>
                </a>

        </div>

    </div>
    <!-- create new product unit ends here-->

    <div class="row" style="margin-top: 20px;">
        <div class="col-lg-4 col-lg-offset-1">
            <h4><strong>Current Products</strong>
            <p>eg.: Cow Milk, Panir, Ghee,...</p>
             <table class="table table-striped table-hover table-responsive">
                    <thead>
                      <tr class="bg-success">
                        <th>Product Name</th>
                        <th>Unit</th>

                      </tr>
                    </thead>
                    <tbody class="active myfont">
                    {% for product in products %}
                       <tr>
                           <td>{{ product.mProduct_name }}</td>
                           <td>{{ product.mProduct_qtyunit }}</td>
                       </tr>
                    {% endfor %}

                    </tbody>
            </table>



        </div>

        <div class="col-lg-4 col-lg-offset-1">
            <h4><strong>Product Units</strong></h4>
            <p>eg.: Kg, Ltr,...</p>
            <table class="table table-striped table-hover table-responsive">
                    <thead>
                      <tr class="bg-success">
                        <th>Unit</th>

                      </tr>
                    </thead>
                    <tbody class="active myfont">
                    {% for unit in units %}
                       <tr>
                           <td>{{ unit.mProductUnit_name }}</td>
                       </tr>
                    {% endfor %}
                    </tbody>
            </table>
        </div>
    </div>



{% endblock %}

{% block extra-js %}
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function() {

            $(".create-product").modalForm({
                formURL: "{% url 'dairyapp:create-product' %}"
            });




        });

    </script>

{% endblock %}